[package]
name = "jackrec_qzt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
jack = "0.11.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
